### ISSUE TITLE
Export "processed" data

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/holpa-platform#54]
Includes 
- Data Dictionary;
- Codebook for choice lists;
- 1 worksheet per data level;

**Comment by alex-thomson222** [comment]
Hi both, I have written some R code to begin with on generating at least the default data dictionary from the default global household form and the agroecology scores dataset that is generated.

These scripts produce tables which look like these

[Agroecology Scores data dictionary.xlsx](https://github.com/user-attachments/files/18010746/Agroecology.Scores.data.dictionary.xlsx)
[Raw global codelists.xlsx](https://github.com/user-attachments/files/18010747/Raw.global.codelists.xlsx)
[Raw global data dictionary.xlsx](https://github.com/user-attachments/files/18010748/Raw.global.data.dictionary.xlsx)

Of course definitely not the final product as we would need to 
- Account for localisations
- read in the form templates from database rather than excel
- make human readable versions of the calculation code
- order the rows by worksheet order (currently everything is in form order + all the multiple select binaries at the bottom)
- As I have with the agroecology scores is it worth having a column for the "old" variable name (in hindsight, its good we have this but platform users probably are not going to need it) - maybe it is optional in the download?

I can produce the equivalent for the fieldwork form

**Comment by alex-thomson222** [comment]
P.S. you may notice on the XLSform I added columns for a repeat flag and the repeat_group_name to help in generating these dictionaries so I can easily mark the correct worksheet name. For now I worked on the assumption of the tables being names repeat_XXX but can easily be changed

**Comment by alex-thomson222** [comment]
@dave-mills @dan-tang-ssd 

I can work without them for now but just a couple things you are probably aware with on the data tables in the database that will need to be filled

- the farm_survey_data_id field for the repeat group tables are currently NULL, for the moment i can see the submission_id is populated so i can use this for testing
- the team_id is not present in the data tables, at the very least I would need this for the farm_survey_data table but i can make it up for now
- i assume the "properties" column will store the booleans for multiple selects. Let me know when you have a version with this populated
- at some point will need the reference tables for those handful of indicators, but i can just import those to my local version temporarily for testing

**Comment by alex-thomson222** [comment]
P.S Should the farm_survey_data table not have only 6 rows rather than 11 as it is mostly information the household survey merged with a small amount of info from the field survey but they in theory should be the same farms?

**Comment by alex-thomson222** [comment]
@dan-tang-ssd @dave-mills 

Assume this isn't just on my end but after the income_count variable (column 186), there is no data in the farm_survey_data table

**Comment by alex-thomson222** [comment]
@dan-tang-ssd 

Additional missing variable

ecological_practices_count

**Comment by dan-tang-ssd** [comment]
Progress update:

1. seasonal_worker_seasons table, added missing column seasonal_labour_months_count
2. farm_survey_data table, added missing column ecological_practices_count
3. farm_survey_data_id column in repeat groups tables is filled in
4. products table, we need to align where to get the data first

**Comment by alex-thomson222** [comment]
Hi @dan-tang-ssd 

Do you have a copy of the updated database with those changes so I can clone it locally

**Comment by dan-tang-ssd** [comment]
@alex-thomson222 - yes yes, sure.

Some more updates:
 
1. farm_survey_data table, populate data from subsidy to farm_loss_text columns
2. seasonal_worker_seasons, column household_members is filled with boolean value
3. products table, I am going to develop a custom hanlding to populate products data by today

---

Latest database dump can be found in below folder:

C:\Users\DanTang\SSD Dropbox\Stats4SD Projects\HOLPA - 2024\database\20241218 Database with Data Retrieved\20241219_1039

**Comment by alex-thomson222** [comment]
@dan-tang-ssd @dave-mills 

Not sure if I already highlighted this but the permanent_workers and seasonal_worker_seasons tables are somewhat incomplete

For the permanent workers, there are only 3 rows with information but looking at the export from ODK Central there should be 18. 13 of which would be of household members (permanent_workers repeat) and 5 externally hired groups (permanent_labourers_s repeat)

For the seasonal, I am only seeing the household members. There should be another 5 rows for the externally hired seasonal workers (seasonal_labourers_s repeat)

**Comment by alex-thomson222** [comment]
Think i forgot to mention this in a previous comment but the ecological_practices table is missing the variable practice_number, need this one to join onto the climate_mitigation_scores table to calculate the indicator

**Comment by alex-thomson222** [comment]
Just a couple non-urgent things to highlight with the reference tables, as we can use the median of the data in place of the reference information these would not be required necessarily for the demo so can wait.

- for yield and fertiliser use, I may just need some help following the data structure so I can link the crop_list_entries table to the crop_id that would be in the crops table as well as the associated team_id e.g. make sure I can connect the value for wheat in a given team to the data

-for income (gni_entries and currencies), similarly will either need these associated to a particular team_id

generally linking the team_id is something i'll need so i can perform certain operations within teams (calculate medians, means, mins, max etc.) so if it is in the farm_survey_data table or easy to join in then that will help. I think for now it is difficult just because the farms table is blank (at least on my end), so i have temporarily just set all entries to be team 1 in my script for testing.

**Comment by dan-tang-ssd** [comment]
Progress updates:

1. ecological_practices table, added missing column "practice_number"
2. products table, populate products data (both pre-defined products and other products)

Latest database dump can be found in below folder:

C:\Users\DanTang\SSD Dropbox\Stats4SD Projects\HOLPA - 2024\database\20241218 Database with Data Retrieved\20241219_1840

**Comment by alex-thomson222** [comment]
thanks @dan-tang-ssd 

I think that means only main outstanding issues would be

- the missing rows and variable (a merging of perm_labour_group_n_workers and perm_labourer_numbers) from the permanent_workers and seasonal_labour_seasons tables
- populating booleans for multiple choice questions into the "properties" json column for each data table (I think only 1 indicator calcualtion uses these at the moment so might be able to demo without them, depending on your thoughts @dave-mills)
- merging the household form data and the fieldwork form data as they both operate at the same farm level, but i think that is difficult currently due to the issue in the ODK form for farm selection on the fieldwork form when we were submitting. this also means populating the farm_survey_data_id column in the fieldwork_sites table. currently though i can merge on submission_id for the demo at least
