### ISSUE TITLE
Submission Retrieval Issue

### ISSUE THREAD

**Issue by dan-tang-ssd** [stats4sd/holpa-platform#95]
@alex-thomson222 @dave-mills 

Hi Alex, Hi Dave, 

I am working on submission retrieval now.

When I retrieve my Household form submission, I got a data type issue for "Total Owned land in HA" with value "NaN".

Questions:
1. The data type of column "area_owned_ha" is a floating point value with 6 d.p., is "NaN" an expected value for this ODK variable?
2. What are the possible values for "area_owned_ha"?
3. There are other "area_xxx_ha" ODK variables, are they similar to "area_owned_ha"?

---

Screen shots:

Dan's submission
![image](https://github.com/user-attachments/assets/bf066bcd-45c7-4c20-bd7e-03824817a46f)

![image](https://github.com/user-attachments/assets/ac90b4de-7d39-4cae-b8be-ca4f46977346)

Alex T's submission
![image](https://github.com/user-attachments/assets/640e921a-d4bd-48ce-8ef5-92062e4f4006)

**Comment by alex-thomson222** [comment]
Hi Dan,

Looking at the csv download, this will be due tot the issues mentioned yesterday regarding the unit csvs. As the conversion for hectares was missing in the csv, the calculation could not be done. I guess rather than leaving the calculated field blank it has put in "NaN" or "Not a Number". So in theory, this should never happen with the real survey as a conversion rate is required to be given by the teams.

**Comment by dan-tang-ssd** [comment]
Thank you Alex.

Um... I may add a temporary hack in filament-odk-link package, just to change "NaN" value to null.
So that I can continue data export work.

**Comment by dan-tang-ssd** [comment]
As a quick workaround, I have added special handling for value "NaN" to filament-odk-link package.
"NaN" value will be changed to null.
